### ISSUE TITLE
How to use luisy with databricks?

### ISSUE THREAD

**Issue by MartinRoth** [boschglobal/luisy#13]

**Comment by GANdalf2357** [comment]
Within this question it is especially interesting to clearify how luisy can be used in combination with spark jobs.
E.g. when using spark jobs the write will also be done within the spark job directly.  
Supporting SparkJobTasks would enpower lusiy when used on databricks but also on other spark backed settings (cloud or non cloud).

**Comment by windisch** [comment]
@MartinRoth: This is partially adressed in #26, can we close this?

**Comment by MartinRoth** [comment]
@windisch yes we can close this.
